export const ecosystemNodes = [
  {
    id: "raw-data",
    title: "Raw Scientific Data",
    type: "source",
    description:
      "Scientific data generated by instruments such as STM, STS, AFM, XPS, and APM systems.",
    position: {
      x: 100,
      y: 250,
    },
  },

  {
    id: "pynxtools",
    title: "Pynxtools",
    type: "core",
    description:
      "Framework for converting scientific data into NeXus-compliant files.",
    position: {
      x: 400,
      y: 250,
    },
  },

  {
    id: "nexus",
    title: "NeXus",
    type: "standard",
    description:
      "Community standard for storing and exchanging scientific data.",
    position: {
      x: 700,
      y: 250,
    },
  },

  {
    id: "nomad",
    title: "NOMAD",
    type: "platform",
    description:
      "Research data management platform providing storage, search, analytics, and DOI services.",
    position: {
      x: 1000,
      y: 250,
    },
  },
];

export const ecosystemConnections = [
  {
    from: "raw-data",
    to: "pynxtools",
    label: "convert",
  },

  {
    from: "pynxtools",
    to: "nexus",
    label: "write",
  },

  {
    from: "nexus",
    to: "nomad",
    label: "ingest",
  },
];